[Blog] add soft delete blog post
MarquezProject/website pull request #21
Opened 2022-10-17 17:08 UTC by merobi-hub

This change adds a blog post about the soft delete feature.

Signed-off-by: Michael Robinson <merobi@gmail.com>

2022-10-17 17:10 UTC, merobi-hub commented
New images will be added in an additional commit.

2022-10-17 19:06 UTC, rossturk requested changes

2022-10-17 19:06 UTC, rossturk commented on contents/blog/soft-delete/index.mdx
> +The idea for this feature came out of a need to keep deleted or renamed datasets and jobs from cluttering the lineage view in Marquez. In Issue [#1736](https://github.com/MarquezProject/marquez/issue
Consider linking Julien's name to his GitHub profile?

2022-10-17 19:06 UTC, rossturk commented on contents/blog/soft-delete/index.mdx
> +image: ./image.svg
On the first blog post the image was 598x266. That's a somewhat random aspect ratio, admittedly.

The two should match, I think. Perhaps we can pick an easier to remember ratio (like 600x270) and make both posts' images match?

2022-10-17 19:06 UTC, rossturk commented on contents/blog/soft-delete/index.mdx
> +banner: ./banner.svg
On the first blog post the banner was 765x123. Same deal here - since there are only two posts, we have options on how to make them both match :)

2022-10-19 16:47 UTC, rossturk approved these changes

2022-10-25 15:23 UTC, merged